spring:
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true

jwt:
  access-time: 3600000 # 1시간
  refresh-time: 2592000000 # 30일
  prefix: Bearer
  header: Authorization
  secret-key: secret
